create table categoria (
    id number generated by default as identity primary key,
    nome varchar(100) not null,
    imagem varchar(4000)
);

create table ingrediente (
    id number generated by default as identity primary key,
    id_categoria integer references categoria(id),
    nome varchar(100) not null
);

